### ISSUE TITLE
Create new SQL Source

### ISSUE THREAD

**Issue by TNohaic** [sentrysoftware/metricshub#157]
### Use case
There is a need for a new Source that could join table like a SQL JOIN would (a 1-n join), that is different from the TableJoin Source (a 1-1 join).

### Specifications
Create a new Source to make SQL queries can be useful and add some freedom to the connector developers.
The parameters of a SQL source would be a list of source tables and a query in a String form.
Example:

```
monitors:
  enclosure:
    discovery;
      sources:
        source_one:[...]
        source_two:[...]
        source_three:
          type: sql
          tables:
          - source: ${source::source_one}
            alias: T1
            columns:
            - name: COL1
              number: 1
              type: VARCHAR(255)
            - name: COL2
              number: 3
              type: BOOLEAN
          - source: ${source::source_two}
            alias: T2
            columns:
            - name: COL1
              number: 2
              type: VARCHAR(255)
            - name: COL2
              number: 4
              type: BOOLEAN
          query: "SELECT T1.COL1, T1.COL2, T2.COL1, T2.COL2 FROM T1 JOIN T2 ON T1.COL1 = T2.COL1;"
```

What happens is that the two sources `source_one` and `source_two ` are created in a temporary database and the query is launched on this database. The result of this query is then used to create the content on the source_three and the database is destroyed.

Since the query is directly launched in the database, it allows all the freedom of a SQL database in regard of data manipulation.

**Comment by NassimBtk** [comment]
To effectively handle sources that may be defined in different jobs, we should use fully qualified paths to refer to each source. This ensures that the SQL engine can correctly identify and fetch the appropriate data tables for query execution. Below is a proposed enhancement to the tables parameter:

**Revised Tables Parameter**
Instead of simply listing the table names like source_one, source_two, use a more descriptive approach that specifies the path to each source, converting each path into a database table in the backend. Here’s how the revised parameter might look:

```yaml
source_three:
  type: sql
  tables:
    - source: "${source::monitors.enclosure.discovery.sources.source_one}"
      as: "source_one"
    - source: "${monitors.disk.discovery.sources.source_disk}"
      as: "source_disk"
  query: "SELECT source_one.column1, source_one.column2, source_disk.column2, source_disk.column3 FROM source_one JOIN source_disk ON source_one.column1 = source_disk.column1;"
```
