### ISSUE TITLE
Develop new connectors selection mechanism

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#2]
# Specification

We aim to streamline the configuration of connectors by consolidating `selectConnectors`, `excludeConnectors`, and `includeConnectorTags` into a single configuration entry named `connectors`. Users are required to include this entry in their `metricshub.yaml` resource configurations.

**Example:**

```yaml
    resources:

      # ECS2-01 Resource Configuration 
      ecs2-01:
        attributes:
          host.name: ecs2-01
          host.type: linux
        protocols:
         snmp:
           community: public
           port: 161
           version: v2c
        connectors: ["#hardware", +DellOpenManage, -MIB2, DellStorageManager]
```

# Scenarios

- Auto detection of `hardware` connectors, without MIB2NT
   ```yaml
   resources:
      my-host:
       connectors: [ "#hardware", "-MIB2NT" ] 
   ```

- Auto detection of `hardware` connectors, with MIB2NT forced
  ```yaml
  resources:
     my-host:
      connectors: [ "#hardware", "+MIB2NT" ]
  ```

- Auto detection with MIB2NT only
   ```yaml
    resources:
       my-host:
        connectors: [ MIB2NT ] 
   ```

- No auto detection - MIB2NT forced
   ```yaml
   resources:
      my-host:
       connectors: [ "+MIB2NT" ]
   ```
  
- The Agent and CLI must read connectors then transmit them to the engine
- The Engine’s Detection strategy needs to be updated to implement the new behavior.
- This means that the HostConfiguration needs to be updated first by replacing the obsolete properties (`selectedConnectors`, `excludedConnectors` and `includeConnectorTags`), with the new `connectors` configuration.

Update the `DetectionStrategy`  to decide how `AutomaticDetection` and `ConnectorSelection` should be called to ensure all the possible behaviors using the connectors variables.
