### ISSUE TITLE
Feature Request: Add `$index` Directive to Collect Row Number in Metric attribute

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#317]
## Background
Let's say we have the following mapping source data:
```
123123SN;500;SSD
456456SN;500;HDD
```

We need to collect the `__display_id` attribute and specify the `$index` directive to collect row numbers. For instance, we want to have 0 for the `500 GB SSD` and 1 for the `500 GB HDD`.

### Example

```yaml
mapping:
  # Mapping source: Source(1)
  source: ${source::source(1)}
  attributes:
    id: $1
    __display_id: $index
    type: $3
  metrics:
    hw.physical_disk.size: $2
```

**Desired Behavior**
We need to add support for a `$index` directive that increments for each row, providing the following mapping:
- For the first row (`123123SN;500;SSD`), the `__display_id` should be 1.
- For the second row (`456456SN;500;HDD`), the `_display_id` should be 2.

## Implementation Details
1. **Initialize Index Counter:** Start by initializing an index counter before processing the source row. (MappingProcessor). Use the loop index.
2. **Iterate Over Source Data:** Increment the index counter for each row.
3. . **Map Attributes:** Use the index counter to set for the attribute. (E.g. `__display_id`).
4. **Sort**: Ensure the source table is consistently ordered, maintaining the same index for instances across different discoveries.
