### ISSUE TITLE
Add the possibility to list many host.ids in one configuration

### ISSUE THREAD

**Issue by CherfaElyes** [sentrysoftware/metricshub#336]
# Specification
Currently, it is possible to configure many hostname as one resource using `host.names` attribute.

```yaml
resourceGroups:
  <resource-group-name>:
    resources:
      <resource-id>:
        attributes:
          host.names: [<hostname1>,<hostname2>, etc.]
          host.type: <type>
        <protocol-configuration>
```

The problem that one may encounter is that all the hosts will share the same `resource-id`. The solution will be to add an attribute called `host.ids` in which we list the different host ids as follows:

```yaml
resourceGroups:
  <resource-group-name>:
    resources:
      <resource-id>:
        attributes:
          host.ids: [<hostId1>,<hostId2>, etc.]
          host.names: [<hostname1>,<hostname2>, etc.]
          host.type: <type>
        <protocol-configuration>
```

Where `<hostId1>` is the ID of `<hostname1>`, and `<hostId2>` the Id of `<hostname2>`, etc.
