### ISSUE TITLE
Update Connector Model to Define Keys Under Monitor and Deprecate Multi-Instance Collect Keys

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#341]
**Description:**
We need to update the MetricsHub connector model to define the `keys` field directly under the monitor section and mark the current multi-instance collect keys as deprecated. This change requires updates to the discovery and simple strategies in the engine to set the monitor ID through the monitor factory based on the identified name in the monitor keys field. 
Additionally, the multi instance collect strategy should retrieve the monitor by the attribute identifier from the `keys` field defined under the monitor instead of the `keys` fields under multi-instance collect.

**Current Implementation:**
```yaml
monitors:
  battery:
    discovery:
      sources:
      ...
    collect:
      type: multiInstance
      keys:
      - id
```

**Proposed Change:**
```yaml
monitors:
  battery:
    keys:
    - id
    discovery:
      sources:
      ...
    collect:
      type: multiInstance
      keys: # deprecated in the code
      - id
```

**Required Updates:**
1. Update the discovery and simple strategies to set the monitor ID through the `MonitorFactory` based on the `keys` field defined under the monitor.
2. Update the collect strategy to get the monitor attribute identifier from the `keys` field under the monitor instead of the `keys` fields defined under the multi-instance collect.

Please update the connector model and related engine strategies accordingly.
