### ISSUE TITLE
Implement simple mapping

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#342]
### Required Connector mapping

```yaml
  memory:
    keys: [id] # key to identify the monitor instance
    simple:
      sources:
        memoryLimit:
         ...
       vendorSource
         ...
      mapping:
        type: simple # csv, single, jsonArray, jsonObject, awk
        # no source for simple type
        attributes:
          vendor: ${source::vendorSource}
        metrics:
          system.memory.limit: ${source::memoryLimit}

```
