### ISSUE TITLE
Exclude non-hardware items from power estimation

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#352]
# Problem

Adding +Linux connector leads to high power estimation.

![image](https://github.com/user-attachments/assets/1cb9de2d-1042-4a42-90c5-412a568e6966)

## Specification

Update the hardware enrichment module to estimate the power only for monitors collected by a connector with `tags` containing `hardware`.

**Comment by MedMaalej** [comment]
The tests were done using the host "**bacon**".

### Before the fix (Reproducing the bug)

We created the following configuration in metricshub.yaml file (**using SNMP**):
(Only the connectors with hardware tag will be processed)
```
resources:
  bacon:
    attributes:
      host.name: bacon
      host.type: linux
    protocols:
      snmp:
        version: v2c
        community: public
        port: 161
        timeout: 120
    connectors: ["#hardware"] 
```
Then, we checked the value of `hw_host_power_watts{host_id="bacon"}`, it was around 130.0

Then, we changed the configuration  in metricshub.yaml file (**using SSH** this time) as follows:
(In addition to hardware connectors, we force the selection of the Linux connector)
```
resources:
  bacon:
    attributes:
      host.name: bacon
      host.type: linux
    protocols:
      ssh:
        timeout: 120
        username: root
        password: nationale
    connectors: ["#hardware","+linux"] 
```

Then, we checked the value of `hw_host_power_watts{host_id="bacon"}`, it was around 1000.0

The curve of the metric `hw_host_power_watts{host_id="bacon"}` value was as follows in Prometheus:

![prometheus_before_dev](https://github.com/user-attachments/assets/a7e21dda-ac51-4296-b2d6-e4731d0c1ac7)

### After the fix

We created the following configuration in metricshub.yaml file (using SNMP):
(Only the connectors with hardware tag will be processed)
```
resources:
  bacon:
    attributes:
      host.name: bacon
      host.type: linux
    protocols:
      snmp:
        version: v2c
        community: public
        port: 161
        timeout: 120
    connectors: ["#hardware"] 
```
Then, we checked the value of `hw_host_power_watts{host_id="bacon"}`, it was around 130.0

Then, we changed the configuration  in metricshub.yaml file (using SSH this time) as follows:
( In addition to hardware connectors, we force the selection of the Linux connector)
```
resources:
  bacon:
    attributes:
      host.name: bacon
      host.type: linux
    protocols:
      ssh:
        timeout: 120
        username: root
        password: nationale
    connectors: ["#hardware","+linux"] 
```

Then, we checked the value of `hw_host_power_watts{host_id="bacon"}`, it was around 120.0

The curve of the metric `hw_host_power_watts{host_id="bacon"} ` value was as follows in Prometheus:

<img width="959" alt="prometheus" src="https://github.com/user-attachments/assets/67544fd2-0c24-4ed2-8162-967caf3849cc">
