### ISSUE TITLE
Develop JDBC Extension

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#422]
### JDBC SQL User's Configuration

**metricshub.yaml**
```yaml
resources:
  db-host:
    attributes:
    # ...
    protocols:
      jdbc:
        username: #
        password: #
        url: #  
        timeout: # 
        type: # 
        port: # 
        database: #
```

| Attribute  | Data Type  | Description                                             | Default Value |
|------------|------------|---------------------------------------------------------|---------------|
| `username` | string     | The username used to authenticate with the database.    | `null`        |
| `password` | char[]     | The password used for authentication (can be encrypted).| `null`        |
| `url`      | char[]     | The connection URL for the database (can be encrypted). | `null` or generated based on `type` and `database`.    |
| `timeout`  | int        | The time in seconds before a connection attempt times out. | `120` seconds          |
| `type`     | string     | The type of database engine (e.g., oracle, postgresql, mariadb, mssql, informix, derby, h2, ...). | `null`  |
| `port`     | int        | The port number to connect to the database.             | `null` or generated based on `type`       |
| `database`     | string | The database name to connect to.             | `null`    |

### SQL Criterion

```yaml
criteria:
- type: sql
  query: # 
  expectedResult: #
  errorMessage:
```

| Attribute Key | Data Type  | Description                                             |
|---------------|------------|---------------------------------------------------------|
| `type`        | string     | Specifies the type of SQL criterion (`sql`). |
| `query`       | string     | The SQL query string to be executed (e.g., `SELECT Column1, Column2 FROM TABLE`). |
| `expectedResult`       | string     | The expected result in the SQL response |
| `errorMessage`       | string     | The error message to display in case of criterion failure |

### SQL Source

```yaml
<source-name>:
   type: sql
   query: # 
```

| Attribute Key | Data Type  | Description                                             |
|---------------|------------|---------------------------------------------------------|
| `type`        | string     | Specifies the type of SQL source (`sql`). |
| `query`       | string     | The SQL query string to be executed (e.g., `SELECT Column1, Column2 FROM TABLE`). |

To differentiate the current source, which executes inner SQL queries using the internal MetricsHub DB engine, we should consider renaming the type of the inner SQL source to reflect its engine-based nature. A suitable option could be `localSql`.

* Should we support for `SELECT * FROM TABLE`
  * If yes, we need to define a new attribute `columns` in the sql source.
* Should we override the url in a source
  * If yes, we need to define a new attribute `url`, that overrides the user's url. It that, in the new `url`, macros should be correctly replaced by the engine.
