### ISSUE TITLE
[BREAKING_CHANGE] Added support for multiple variable values for the same connector

### ISSUE THREAD

**Issue by CherfaElyes** [sentrysoftware/metricshub#435]
# Specification
Currently, it is possible to define connector variables values as follows:

``` yaml
resources:
  <host_id>:
    attributes:
      host.name: <hostname>
      host.type: linux
    protocols:
      ssh:
        username: <username>
        password: <password>
    variables:
      <connectorId>:
        <variableName>: <variableValue>
```
This does not allow to use the same connector more than once. To remedy, we would like to implement the following configuration in order to be able to use the same connector many times with different connector variables values:

``` yaml
  additionalConnectors:
    <CustomConnectorId1>: 
      uses: <ConnectorId> # If not specified, the default is the key name
      variables:
        <VariableName>: <VariableValue>
      force: false # default true
    <CustomConnectorId2>: 
      uses: <ConnectorId> # If not specified, the default is the key name
      variables:
        <VariableName>: <VariableValue>
      force: false # default true
```

# To do
- [x] 1. Update the resourceConfig to take into consideration the `additionalConnectors` section.
- [x] 2. Make all the necessary changes in the engine & the agent to adapt.
  - [x] 2.1 Add AdditionalConnectorsConfig & deserialize them
  - [x] 2.2 Update ConnectorTemplateLibraryParser to handle the changes.
- [x] 3. Adapt unit tests.
- [x] 4. Test the changes on MetricsHub.
- [x] 5. Update the connectors maven plugin to correctly display connector variables and generate `metricshub.yaml`.
      https://github.com/sentrysoftware/metricshub-connector-maven-plugin/issues/63
- [x] 6. Update MetricsHub example to give an example of the `additionalConnectors` section.
- [x] 7. Modify MetricsHub documentation to update how to configure connector variables.
- [x] 8. Update metricshub-community connectors 
      https://github.com/sentrysoftware/metricshub-community-connectors/issues/128
- [x] 9. Add `parameterized` tag to connectors with variables
      https://github.com/sentrysoftware/metricshub-community-connectors/issues/138
- [ ] 10. Modify MetricsHub schema in schemastore.
- [ ] 11. Add CLI options to additional connectors and connector variables 
       #357
