### ISSUE TITLE
Moved the localhost resource configuration to the `data center 1` resource group in `metricshub-example.yaml`

### ISSUE THREAD

**Issue by CherfaElyes** [sentrysoftware/metricshub#450]
# Specification
Currently, in the metricshub.yaml examples, the localhost is not located under a resource group.
```yaml
# Simple resource configuration
resources:
  localhost:
    attributes:
      host.name: localhost
      host.type: windows
    protocols:
      wmi:
        timeout: 120
```

# To do
Move the localhost configuration example under data center 1 resource group.
```yaml
resourceGroups:
  data-center-1:
    attributes:
      site: data center 1
    resources:
      localhost:
        attributes:
          host.name: localhost
          host.type: windows
        protocols:
          wmi:
            timeout: 120
```

To do on both windows & linux examples
