### ISSUE TITLE
Support shared-characteristics for centralized resource configuration

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#468]
**Issue Description:**
Currently, MetricsHub supports configuring shared characteristics only within resource groups. We would like to extend this feature to enable shared characteristics when configuring centralized resources (global resources). This enhancement will simplify the configuration process for users managing multiple resources with similar attributes.

### Feature Description

- **Shared Characteristics**: For resources with common characteristics, such as device type, protocols, and credentials, grouped configuration syntax should be allowed:
  ```yaml
  resources:
    <resource-id>:
      attributes:
        host.names: [<hostname1>, <hostname2>, etc.]
        host.type: <type>
      <protocol-configuration>

  resourceGroups:
  # Already supported
  ```
