### ISSUE TITLE
Update the Connector `platforms` field to string array

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#530]
**Specification**

Modify the engine model to support platforms as an array and ensure the parser can handle both arrays and comma-separated strings (backward-compatibility).

Accepted Connector inputs:

```yaml
connector:
  displayName: SuperMicro (REST)
  platforms: SuperMicro
```

```yaml
connector:
  displayName: EMC Navisphere CLI (Local User)
  platforms:
  - EMC CLARiiON
  - EMC VNX
```
**Technical specifications**

Update the field platforms under **ConnectorIdentity** (From String to Set of String)

```
/**
* The platforms on which the connector operates.
*/
@JsonDeserialize(using = PlatformsDeserializer.class)
@JsonSetter(nulls = SKIP)
private Set<String> platforms = new HashSet<>();
```
We need to add **PlatformsDeserializer** which is a custom deserializer for the platforms field. It extends  **AbstractNonBlankNonNullInCollectionDeserializer**.

**Testing**

Case 1: the platforms field is a string with commas
Case 2: the platforms field is a set

- Unit tests
- Functional tests
