### ISSUE TITLE
Remove mandatory `id` attribute requirement for collected metrics

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#626]
#### **Description** 

Currently, the MetricsHub engine enforces that each metric mapping contains an explicitly defined attribute, often requiring an `id` attribute. However, when **`keys` attributes are specified at the monitor level**, the engine should **automatically use the available keys to identify the monitored entity**  

This enhancement would:
- **Prevent failures when an attribute (e.g., `id`) is missing but an alternative keys are defined.**  
- **Automatically apply the keys to the mapped metrics**  

#### **Expected Behavior**  
- The **engine should automatically assign the attribute from `keys` to all mapped metrics.**  
- The engine should **only fail if the attributes in `keys` are not found** in the mapping.  

##### **Proposed Behavior (Works Automatically)**  
```yaml
cpu:
  keys: [ another_attribute_id ] 
  discovery:
    sources:
      # ...
    mapping:
      source: "${source::source(1)}"
      attributes:
        another_attribute_id: $2  
```
