### ISSUE TITLE
Manage the new format of constant references for better clarity

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#8]
# Specification

Constants should be referred to with `${constant::<constant_name>}` for clarity and consistency.

Example: 
```yaml
        source(1):
          # Get the model name
          # ModelName;SerialNumber;DeviceSlotID;
          type: snmpTable
          oid: 1.3.6.1.4.1.${constant::_OID}.2.235.1.1.1
```

Update the parser (ConstantsProcessor) to correctly replace constant references.
