### ISSUE TITLE
Document how to resolve `out of order sample` errors on Prometheus

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#97]
If you have many metricshub agents sending metrics to 1 Prometheus serveur and want to avoid out of order sample errors, you need to add this in your prometheus.yaml

```yaml
storage:
  tsdb:
    # A 10min time window is enough because it can easily absorb retries and network delays.
    out_of_order_time_window: 10m
```
